### ISSUE TITLE
Problems when running with bulk files

### ISSUE THREAD

**Issue by awfulcitizen** [rustymyers/warranty#12]
when I run the script one by one, it works fine.  When I run it with a bulk file:

`./apple-warranty.sh -b 10-macs.csv -o ~/Desktop/ -f csv -n warranty-info.csv -v -k`

This is how my output .csv looks:
```
SerialNumber	 WarrantyExpires	 WarrantyStatus	 ModelName	 AsdVers	 IsAniPhone	 iPhoneCarrier	 PartDescript	 Display Serial Numbers
C1MMD183DV30								
	 Out Of Coverage	 Out Of Coverage	 	 unknown				
unknown								
unknown								
3X102								
3X106								
3X106								
3S108								
3S108								
3S108								
3S108								
3S108								
3S108								
3S108								
```

**Comment by rustymyers** [comment]
I reproduced this once, but I've been unable to a second time nor determine why it happened. Does this occur every time you run the script?

**Comment by awfulcitizen** [comment]
Yes it does.  Can I send you the .csv file I am using to see if you could
re-create?

On Thu, Apr 28, 2016 at 2:04 PM, Rusty Myers <notifications@github.com>
wrote:

> I reproduced this once, but I've been unable to a second time nor
> determine why it happened. Does this occur every time you run the script?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rustymyers/warranty/issues/12#issuecomment-215530103>
>



-- 
Gilbert J. Palau
gilbertpalau@gmail.com
http://gilbertopalau.com

**Comment by rustymyers** [comment]
Yes, please email it to me rustymyers at gmail.com. Thanks

**Comment by rustymyers** [comment]
The issue ended up being the csv of serials had CRLF line endings, which caused the variables in the script to have incorrect returns. Added code to find and fix the line endings before checking warranty status.

**Comment by ghost** [comment]
Hi! I’ve signed up for a spam filtering service called BitBounce and I added you to my “whitelist”. That means you can email me and your emails will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Bitcoin for their email to get to my inbox. A cleaner inbox and more money? Win! You should check it out!

Sign up to get paid for emails here: https://bitbounce.io?ref=bitbounce

--

Unsubscribe from Gilbert Palau's whitelist notification emails here: https://www.turing-cloud.com/unsubscribe_from_whitelist_email_notifications/3361472512
