### ISSUE TITLE
Apple Care information

### ISSUE THREAD

**Issue by hreality** [rustymyers/warranty#14]
Could this be updated to reflect active apple care support.. ie. my system is out of warranty but I still have 2yrs apple care...

**Comment by rustymyers** [comment]
Unfortunately, this project is dead. Due to the changes Apple has made, we are no longer able to return any warranty data through the web service. Alternatives are to use GSX APIs or this (python script)[https://github.com/pudquick/pyMacWarranty] to return warranty information.
Thanks,
Rusty Myers
